version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5000:8080
    volumes:
      - ..:/workspace:cached
    command: /bin/bash -c "source /workspace/.venv/dd-discord-bot/bin/activate && cd /workspace && pip install -r requirements.txt && python serve.py"
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/bash -c "source /workspace/.venv/dd-discord-bot/bin/activate && cd /workspace && pip install -r requirements.txt && python bot.py"

  mongodb:
    image: mongo:latest
    hostname: mongodb
    restart: unless-stopped
    volumes:
      - /home/ec2-user/appdata/dd-bot-db/db:/data/db
      - /home/ec2-user/appdata/dd-bot-db/config:/data/configdb
    # As in the "app" service, use "forwardPorts" in **devcontainer.json** to forward an app port locally.
networks:
  default:
    external:
      name: dd_bot